# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Copia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=20)),
                ('copia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotecas.Copia')),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='prestamo',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotecas.Socio'),
        ),
        migrations.AddField(
            model_name='copia',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotecas.Libro'),
        ),
    ]
