# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
