# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecas', '0002_auto_20170520_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='id',
            new_name='isbn',
        ),
        migrations.RemoveField(
            model_name='copia',
            name='id',
        ),
        migrations.AddField(
            model_name='copia',
            name='nro_inventario',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
