# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecas', '0003_auto_20170520_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copia',
            name='nro_inventario',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
