# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecas', '0004_auto_20170606_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='fecha_comienzo',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
