# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecas', '0005_prestamo_fecha_comienzo'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='fecha_nacimiento',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
