# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecas', '0006_socio_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestamo',
            name='fecha_fin',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
