# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecas', '0007_auto_20170618_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_comienzo',
            field=models.DateField(),
        ),
    ]
